name: DEPLOY FRONTEND SOLUTEST

on:
  pull_request:
    branches: [main]

env:
  REGISTRY: ${{ secrets.GCP_REGION }}-docker.pkg.dev
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REPOSITORY: ${{ secrets.GCP_APP_NAME }}
  IMAGE_NAME: ${{ secrets.GCP_APP_NAME }}
  REGION: ${{ secrets.GCP_REGION }}
  GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
  SERVICE_NAME: ${{ secrets.GCP_APP_NAME }}
  PORT: ${{ secrets.PORT }}
  NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
  NEXT_PUBLIC_MY_URL: ${{ secrets.NEXT_PUBLIC_MY_URL }}
  NEXT_PUBLIC_SSO_URL: ${{ secrets.NEXT_PUBLIC_SSO_URL }}
  NEXT_PUBLIC_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_CLIENT_ID }}

jobs:
  deploy:
    name: Build, Push, and Deploy to Cloud Run
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGISTRY }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg PORT=${{ env.PORT }} \
            --build-arg NEXT_PUBLIC_API_BASE_URL=${{ env.NEXT_PUBLIC_API_BASE_URL }} \
            --build-arg NEXT_PUBLIC_MY_URL=${{ env.NEXT_PUBLIC_MY_URL }} \
            --build-arg NEXT_PUBLIC_SSO_URL=${{ env.NEXT_PUBLIC_SSO_URL }} \
            --build-arg NEXT_PUBLIC_CLIENT_ID=${{ env.NEXT_PUBLIC_CLIENT_ID }} \
            -t ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:pr-${{ github.event.pull_request.number }} \
            -t ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker images
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:pr-${{ github.event.pull_request.number }}
          docker push ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
          flags: |
            --allow-unauthenticated
            --port=${{ env.PORT }}
            --memory=512Mi
            --cpu=1
            --min-instances=0
            --max-instances=10
            --concurrency=80
